{
 "title": "ProfileServiceDashboard",
 "description": "Service profile",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Profile CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "profile_service_cpu_usage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Profile Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "profile_service_memory_usage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Profile RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(profile_service_request_duration_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Profile Request Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 8, "y": 8 },
   "targets": [
    { "expr": "profile_service_requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Profile Request Error",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 8 },
   "targets": [
    {
     "expr": "profile_service_requests_error_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Profile Trraffic Outbound",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "expr": "sort_desc(profile_service_traffic_outbound_bytes_sum)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Profile Traffic Inbound",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "expr": "sort_desc(profile_service_traffic_inbound_bytes_sum)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}